table Medidas
	lineageTag: 3261a397-fa1c-4b1a-84c7-fdc49f1a50a3

	measure Target = ```
			2.5
			
			```
		lineageTag: 6d82e502-5318-440a-a0cf-a44f753b00f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MediaSatisfacaoValor = ```
			
			AVERAGEX(
			    ALLSELECTED(satisfacao),
			    satisfacao[Media_Satisfacao]
			)
			
			```
		lineageTag: a5014958-8d24-4584-b29d-336892df2f54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MediaEngajamento = ```
			
			AVERAGEX(
			    ALLSELECTED(satisfacao),
			    satisfacao[Media_Engajamento]
			)
			
			```
		lineageTag: 0cf40135-52c1-4488-a1d7-73299a9d995d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MediaSalarioFuncao = ```
			
			AVERAGE(salario_departamento[Media_Salario_Anual])
			
			```
		lineageTag: d5542972-f4e7-4dc7-88b3-e50df4fbbdbf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MediaAnoEmpresa = ```
			
			AVERAGEX(
			    ALLSELECTED(tempo_empresa),
			    tempo_empresa[Media_Anos_Empresa]
			)
			
			```
		lineageTag: 1a13231f-fbb4-477c-9df4-e3897650df32

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MediaAnoFuncao =
			
			AVERAGEX(
			    ALLSELECTED(tempo_empresa),
			    tempo_empresa[Media_Anos_Funcao]
			)
		lineageTag: 5348a4d5-d110-4577-9506-5d2db890dccd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		formatString: 0
		lineageTag: d8633346-ab4f-407d-8fed-ec078f97e6ca
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = fa51d4957c7c4b3ebb470b8c18b14d33

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

